// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlJ2ufB9M6KBeFl2P9DpeHEh53f2ktYA8',
    appId: '1:736530110989:web:da94bfcb8d7242e2ed1344',
    messagingSenderId: '736530110989',
    projectId: 'molten-raceway-419617',
    authDomain: 'molten-raceway-419617.firebaseapp.com',
    storageBucket: 'molten-raceway-419617.appspot.com',
    measurementId: 'G-W0GN09N1RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYQHlveU4tVsJtbgAyyi5v9j4zp_vze4',
    appId: '1:736530110989:android:bb8593f9d09855f6ed1344',
    messagingSenderId: '736530110989',
    projectId: 'molten-raceway-419617',
    storageBucket: 'molten-raceway-419617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrGSsevZwGHtSJSI4oYf2pTP0poMipwM',
    appId: '1:736530110989:ios:a07b481eab3f44b5ed1344',
    messagingSenderId: '736530110989',
    projectId: 'molten-raceway-419617',
    storageBucket: 'molten-raceway-419617.appspot.com',
    iosBundleId: 'com.example.kotlinproj',
  );
}
